routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//->middleware('auth');


Route::middleware(['auth'])->group(function () {

    Route::resource('accesslevels', 'AccessLevelController');
    Route::resource('categories', 'CategoryController');
    Route::resource('departments', 'DepartmentController');
    Route::get('projects/create/{category_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::resource('projects', 'ProjectsController');

    Route::resource('tasks', 'TasksController');
    Route::get('tasks/{task_id}', 'TasksController@edit');
    Route::post('tasks/{task_id}', 'TasksController@update');
    Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');

    
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'name',
        'description',
        'category_id',
        'user_id',
        

    ];


    public function users(){
		return $this->belongsToMany('App\User');
    }

    

    public function category(){
		return $this->belongsTo('App\Category');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\Category;
use App\User;
use Auth;
use GuzzleHttp;
use GuzzleHttp\Subscriber\Oauth\Oauth1;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index()
     {
         
         if( Auth::check() ){
             $projects = Project::where('user_id', Auth::user()->id)->get();
 
              return view('projects.index', ['projects'=> $projects]);  
         }
         return view('auth.login');
     }
 
   public function indexAll()
     {
         
         if( Auth::check() ){
             $projects = Project::all();
 
              return view('projects.all', ['projects'=> $projects]);  
         }
         return view('auth.login');
     }
     

     /**
      * Show the form for creating a new resource.
      *
      * @return \Illuminate\Http\Response
      */
     public function create( $category_id = null )
     {
         //

         $categories = null;
         if(!$category_id){
            $categories = Category::where('user_id', Auth::user()->id)->get();
         }
 
         return view('projects.create',['category_id'=>$category_id, 'categories'=>$categories]);
     }
 
     /**
      * Store a newly created resource in storage.
      *
      * @param  \Illuminate\Http\Request  $request
      * @return \Illuminate\Http\Response
      */
     public function store(Request $request)
     {
         //
 
         if(Auth::check()){
             $project = Project::create([
                 'name' => $request->input('name'),
                 'description' => $request->input('description'),
                 'category_id' => $request->input('category_id'),
                 'user_id' => Auth::user()->id
             ]);
 
 
             if($project){
                 return redirect()->route('projects.show', ['project'=> $project->id])
                 ->with('success' , 'project created successfully');
             }
 
         }
         
             return back()->withInput()->with('errors', 'Error creating new project');
 
     }

    
 
     /**
      * Display the specified resource.
      *
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function show(Project $project)
     {
       
        $project = Project::find($project->id);
 
        $comments = $project->comments;
         return view('projects.show', ['project'=>$project, 'comments'=> $comments ]);
     }
 
     /**
      * Show the form for editing the specified resource.
      *
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function edit(Project $project)
     {
         //
         $project = Project::find($project->id);
         
         return view('projects.edit', ['project'=>$project]);
     }
 
     /**
      * Update the specified resource in storage.
      *
      * @param  \Illuminate\Http\Request  $request
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function update(Request $request, project $project)
     {
        
 
       $projectUpdate = Project::where('id', $project->id)
                                 ->update([
                                         'name'=> $request->input('name'),
                                         'description'=> $request->input('description')
                                 ]);
 
       if($projectUpdate){
           return redirect()->route('projects.show', ['project'=> $project->id])
           ->with('success' , 'project updated successfully');
       }
       //redirect
       return back()->withInput();
 
 
       
     }
 
     /**
      * Remove the specified resource from storage.
      *
      * @param  \App\project  $project
      * @return \Illuminate\Http\Response
      */
     public function destroy(Project $project)
     {
 
         $findproject = Project::find( $project->id);
         if($findproject->delete()){
             
             //redirect
             return redirect()->route('projects.index')
             ->with('success' , 'project deleted successfully');
         }
 
         return back()->withInput()->with('error' , 'project could not be deleted');
         
 
     }
}

resources/views/projects/all.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-6 col-lg-6 col-md-offset-3  col-lg-offset-3">
    <div class="panel panel-primary ">
    <div class="panel-heading">All Projects <a  class="pull-right btn btn-primary btn-sm" href="/projects/create">
    Create new</a> </div>
    <div class="panel-body">
        

    <ul class="list-group">
    @foreach($projects as $project)
        <li class="list-group-item"> 
        <i class="fa fa-play" aria-hidden="true"></i>
        <a href="/projects/{{ $project->id }}" >{{ $project->name }}</a></li>
    @endforeach
    </ul>


    </div>
    </div>
</div>

@endsection

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')



     <div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3 " style="background: white; ">
    <h1>Create new project </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('projects.store') }}">
                            {{ csrf_field() }}


                            <div class="form-group">
                                <label for="project-name">Name<span class="required">*</span></label>
                                <input   placeholder="Enter name"  
                                          id="project-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                           />
                                  </div>

                                  @if($categories == null)
                                  <input   
                                  class="form-control"
                                  type="hidden"
                                          name="category_id"
                                          value="{{ $category_id }}"
                                           />
                                  </div>

                                  @endif

                            @if($categories != null)
                            <div class="form-group">
                                <label for="category-content">Select category</label>

                                <select name="category_id" class="form-control" > 

                                @foreach($categories as $category)
                                        <option value="{{$category->id}}"> {{$category->name}} </option>
                                      @endforeach
                                </select>
                            </div>
                            @endif

                            <div class="form-group">
                                <label for="project-content">Description</label>
                                <textarea placeholder="Enter description" 
                                          style="resize: vertical" 
                                          id="project-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">

                                          
                                          </textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   

      </div>
</div>




    @endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')



<div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3  " style="background: white;">
<h1>Update project </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('projects.update',[$project->id]) }}">
                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="put">

                            <div class="form-group">
                                <label for="project-name">Name<span class="required">*</span></label>
                                <input   placeholder="Enter name"  
                                          id="project-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $project->name }}"
                                           />
                            </div>


                            <div class="form-group">
                                <label for="company-content">Description</label>
                                <textarea placeholder="Enter description" 
                                          style="resize: vertical" 
                                          id="project-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">
                                          {{ $project->description }}</textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   

      </div>
</div>





    @endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-6 col-lg-8 col-md-offset-3  col-lg-offset-3">
    <div class="panel panel-primary ">
    <div class="panel-heading">Projects <a  class="pull-right btn btn-primary btn-sm" href="/projects/create">
    Create new</a> </div>
    <div class="panel-body">
        

    <ul class="list-group">
    @foreach($projects as $project)
        <li class="list-group-item"> 
        <i class="fa fa-play" aria-hidden="true"></i>
        <a href="/projects/{{ $project->id }}" >{{ $project->name }}</a></li>
    @endforeach
    </ul>


    </div>
    </div>
</div>

@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
   
     <div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3 ">
      <div class="well well-lg" >
        <h1>{{ $project->name }}</h1>
        <p class="lead">{{ $project->description }}</p>
         <li><a href="/projects/{{ $project->id }}/edit">
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 
              Edit</a></li>

            @if($project->user_id == Auth::user()->id)
            
              <li>
              <i class="fa fa-power-off" aria-hidden="true"></i>
              <a   
              href="#"
                  onclick="
                  var result = confirm('Are you sure you wish to delete this project?');
                      if( result ){
                              event.preventDefault();
                              document.getElementById('delete-form').submit();
                      }
                          "
                          >
                  Delete
              </a>

              <form id="delete-form" action="{{ route('projects.destroy',[$project->id]) }}" 
                method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
              </form>

              </li>
 @endif
                </div>

      <div class="row  col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px; ">
<br/>

@include('comments.comments')


<div class="row container-fluid">

<form method="post" action="{{ route('comments.store') }}">
                            {{ csrf_field() }}


                            <input type="hidden" name="commentable_type" value="App\Project">
                            <input type="hidden" name="commentable_id" value="{{$project->id}}">


                            <div class="form-group">
                                <label for="comment-content">Comment</label>
                                <textarea placeholder="Enter comment" 
                                          style="resize: vertical" 
                                          id="comment-content"
                                          name="body"
                                          rows="3" spellcheck="false"
                                          class="form-control autosize-target text-left">

                                          
                                          </textarea>
                            </div>




                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   


                        </div>

                      

      </div>
</div>
   
<div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3">

            </ol>
<hr/>

      
              </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
<br/>

            </ol>

          </div>

        </div>

@endsection