routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//->middleware('auth');


Route::middleware(['auth'])->group(function () {

    Route::resource('accesslevels', 'AccessLevelController');
    Route::resource('categories', 'CategoryController');
    Route::resource('departments', 'DepartmentController');
    Route::get('projects/create/{category_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::resource('projects', 'ProjectsController');

    Route::resource('tasks', 'TasksController');
    Route::get('tasks/{task_id}', 'TasksController@edit');
    Route::post('tasks/{task_id}', 'TasksController@update');
    Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');

    
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;




class User extends Authenticatable
{

     use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'email', 
        'password',
 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

  
    
    public function role(){
        return $this->belongsTo('App\Role');
    }

    public function categories(){
        return $this->hasMany('App\Category');
    }
    

    public function tasks()
    {
        return $this->belongsToMany('App\Task');
    }


    //many to many relationship
    public function projects()
    {
        return $this->belongsToMany('App\Project');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Validator;
use Auth;
class UsersController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       if( Auth::check() ){


            $users = User::all();

             return view('users.index', ['users'=> $users]);  
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
   protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
    }
    public function store(Request $data)
    {
        if(Auth::check()){
            $user = User::create([
                'name' => $data->input('name'),
                'email' => $data->input('email'),
                'password' => bcrypt($data['password']),

            ]);


            if($user){
                return redirect()->route('users.show', ['user'=> $user->id])
                ->with('success' , 'User created successfully');
            }

        }
        
            return back()->withInput()->with('errors', 'Error creating new user');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
       $user = User::find($user->id);

        return view('users.show', ['user'=>$user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $user = User::find($user->id);
        
        return view('users.edit', ['user'=>$user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $data, User $user)
    {
        
      $userUpdate = User::where('id', $user->id)
                                ->update([
                                        'name'=> $data->input('name'),
                                        'email'=> $data->input('data'),
                                         'password' => bcrypt($data['password']),

                                ]);

      if($userUpdate){
          return redirect()->route('users.show', ['user'=> $user->id])
          ->with('success' , 'User updated successfully');
      }
      //redirect
      return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        
        $findUser = User::find( $user->id);
		if($findUser->delete()){
            
            //redirect
            return redirect()->route('users.index')
            ->with('success' , 'User deleted successfully');
        }

        return back()->withInput()->with('error' , 'User could not be deleted');
        
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')



     
     <div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3 " style="background: white;">
    <h1>Create new user </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('users.store') }}">
                            {{ csrf_field() }}


                            <div class="form-group">
                                <label for="user-name">Name<span class="required">*</span></label>
                                <input   placeholder="Enter name"  
                                          id="user-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                           />
                            </div>


                             <div class="form-group">
                                <label for="user-email">Email<span class="required">*</span></label>
                                <input type="email"  placeholder="Enter email"  
                                          id="user-email"
                                          required
                                          name="email"
                                          spellcheck="false"
                                          class="form-control"
                                           />
                            </div>
                            <div class="form-group">
                                <label for="user-password">Password<span class="required">*</span></label>
                                <input type="password"  placeholder="Enter password"  
                                          id="user-password"
                                          required
                                          name="password"
                                          spellcheck="false"
                                          class="form-control"
                                           />
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   

      </div>
</div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">

        </div>


    @endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')



<div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3 " style="background: white;">
<h1>Update User </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('users.update',[$user->id]) }}">
                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="put">

                            <div class="form-group">
                                <label for="user-name">Name<span class="required">*</span></label>
                                <input   placeholder="Enter name"  
                                          id="user-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $user->name }}"
                                           />
                            </div>

                            <div class="form-group">
                                <label for="user-email">Email<span class="required">*</span></label>
                                <input type="email" required=""  placeholder="Enter email"  
                                          id="user-email"
                                          required
                                          name="email"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $user->email }}"
                                           />
                            </div>

                        <div class="form-group">
                                <label for="user-password">Password<span class="required">*</span></label>
                                <input  type="password" placeholder="Enter password"  
                                          id="user-name"
                                          required
                                          name="password"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $user->password }}"
                                           />
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   

      </div>
</div>





    @endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3">
    <div class="panel panel-primary ">
    <div class="panel-heading">Users <a  class="pull-right btn btn-primary btn-sm" href="/users/create">
    Create new</a> </div>
    <div class="panel-body">
        

    <ul class="list-group">
    @foreach($users as $user)
        <li class="list-group-item"> 
        <i class="fa fa-play" aria-hidden="true"></i>
        <a href="/users/{{ $user->id }}" >{{ $user->name }}</a></li>
    @endforeach
    </ul>


    </div>
    </div>
</div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')


     
     <div class="col-md-8 col-lg-8 col-md-offset-3  col-lg-offset-3 ">
      <!-- The justified navigation menu is meant for single line per list item.
           Multiple lines will require custom code not provided by Bootstrap. -->
      <!-- Jumbotron -->
      <div class="jumbotron" >
        <h1>{{ $user->name }}</h1>
        <p class="lead">{{ $user->email }}</p>
   <a href="/users/{{ $user->id }}/edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> 
Edit</a>
              

                            <i class="fa fa-power-off" aria-hidden="true"></i>
    
              <a   
              href="#"
                  onclick="
                  var result = confirm('Are you sure you wish to delete this User?');
                      if( result ){
                              event.preventDefault();
                              document.getElementById('delete-form').submit();
                      }
                          "
                          >
                  Delete
              </a>

              <form id="delete-form" action="{{ route('users.destroy',[$user->id]) }}" 
                method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
              </form>

 
              
              
              
      </div>

 
</div>





    @endsection